config/routes.rb
Dinning::Application.routes.draw do
  resources :departments

  resources :companies

  resources :foots

  match ':controller(/:action(/:id(.:format)))'

end

app/models/company.rb
class Company < ActiveRecord::Base
end

app/models/department.rb
class Department < ActiveRecord::Base
	belongs_to :company
end

app/models/foot.rb
class Foot < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @companies }
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @company = Company.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/new
  # GET /companies/new.json
  def new
    @company = Company.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/1/edit
  def edit
    @company = Company.find(params[:id])
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(params[:company])

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render json: @company, status: :created, location: @company }
      else
        format.html { render action: "new" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /companies/1
  # PUT /companies/1.json
  def update
    @company = Company.find(params[:id])

    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :ok }
    end
  end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  # GET /departments
  # GET /departments.json
  def index
    @departments = Department.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @departments }
    end
  end

  # GET /departments/1
  # GET /departments/1.json
  def show
    @department = Department.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @department }
    end
  end

  # GET /departments/new
  # GET /departments/new.json
  def new
    @department = Department.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @department }
    end
  end

  # GET /departments/1/edit
  def edit
    @department = Department.find(params[:id])
  end

  # POST /departments
  # POST /departments.json
  def create
    @department = Department.new(params[:department])

    respond_to do |format|
      if @department.save
        format.html { redirect_to @department, notice: 'Department was successfully created.' }
        format.json { render json: @department, status: :created, location: @department }
      else
        format.html { render action: "new" }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /departments/1
  # PUT /departments/1.json
  def update
    @department = Department.find(params[:id])

    respond_to do |format|
      if @department.update_attributes(params[:department])
        format.html { redirect_to @department, notice: 'Department was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1
  # DELETE /departments/1.json
  def destroy
    @department = Department.find(params[:id])
    @department.destroy

    respond_to do |format|
      format.html { redirect_to departments_url }
      format.json { head :ok }
    end
  end
end

app/controllers/foots_controller.rb
class FootsController < ApplicationController
  # GET /foots
  # GET /foots.json
  def index
    @foots = Foot.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @foots }
    end
  end

  # GET /foots/1
  # GET /foots/1.json
  def show
    @foot = Foot.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @foot }
    end
  end

  # GET /foots/new
  # GET /foots/new.json
  def new
    @foot = Foot.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @foot }
    end
  end

  # GET /foots/1/edit
  def edit
    @foot = Foot.find(params[:id])
  end

  # POST /foots
  # POST /foots.json
  def create
    @foot = Foot.new(params[:foot])

    respond_to do |format|
      if @foot.save
        format.html { redirect_to @foot, notice: 'Foot was successfully created.' }
        format.json { render json: @foot, status: :created, location: @foot }
      else
        format.html { render action: "new" }
        format.json { render json: @foot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /foots/1
  # PUT /foots/1.json
  def update
    @foot = Foot.find(params[:id])

    respond_to do |format|
      if @foot.update_attributes(params[:foot])
        format.html { redirect_to @foot, notice: 'Foot was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @foot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foots/1
  # DELETE /foots/1.json
  def destroy
    @foot = Foot.find(params[:id])
    @foot.destroy

    respond_to do |format|
      format.html { redirect_to foots_url }
      format.json { head :ok }
    end
  end
end

app/controllers/hola_controller.rb
class HolaController < ApplicationController
  def mundo
    render :text => "Hola <b>Mundo</b>"
  end
  def caluroso
    @valor=params[:id].to_i
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/foots_helper.rb
module FootsHelper
end

app/helpers/hola_helper.rb
module HolaHelper
end

app/views/companies/_form.html.haml
= form_for @company, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .control-group
    = f.label :addres, :class => 'control-label'
    .controls
      = f.text_field :addres, :class => 'text_field'
  .control-group
    = f.label :active, :class => 'control-label'
    .controls
      = f.check_box :active, :class => 'check_box'
  .control-group
    = f.label :ciut, :class => 'control-label'
    .controls
      = f.text_field :ciut, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), companies_path, :class => 'btn'

app/views/companies/edit.html.haml
- model_class = Company
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/companies/index.html.haml
- model_class = Company
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:addres)
      %th= model_class.human_attribute_name(:active)
      %th= model_class.human_attribute_name(:ciut)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @companies.each do |company|
      %tr
        %td= link_to company.id, company_path(company)
        %td= company.name
        %td= company.addres
        %td= company.active
        %td= company.ciut
        %td=l company.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_company_path(company), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), company_path(company), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_company_path, :class => 'btn btn-primary'

app/views/companies/new.html.haml
- model_class = Company
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/companies/show.html.haml
- model_class = Company
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @company.name
%p
  %strong= model_class.human_attribute_name(:addres) + ':'
  %br
  = @company.addres
%p
  %strong= model_class.human_attribute_name(:active) + ':'
  %br
  = @company.active
%p
  %strong= model_class.human_attribute_name(:ciut) + ':'
  %br
  = @company.ciut

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), companies_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_company_path(@company), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), company_path(@company), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/departments/_form.html.haml
= form_for @department, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :company_id, :class => 'control-label'
    .controls
      = f.number_field :company_id, :class => 'number_field'
  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), departments_path, :class => 'btn'

app/views/departments/edit.html.haml
- model_class = Department
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/departments/index.html.haml
- model_class = Department
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:company_id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @departments.each do |department|
      %tr
        %td= link_to department.id, department_path(department)
        %td= department.company_id
        %td= department.name
        %td=l department.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_department_path(department), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), department_path(department), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_department_path, :class => 'btn btn-primary'

app/views/departments/new.html.haml
- model_class = Department
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/departments/show.html.haml
- model_class = Department
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:company_id) + ':'
  %br
  = @department.company_id
%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @department.name

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), departments_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_department_path(@department), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), department_path(@department), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/foots/_form.html.erb
<%= form_for(@foot) do |f| %>
  <% if @foot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@foot.errors.count, "error") %> prohibited this foot from being saved:</h2>

      <ul>
      <% @foot.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/foots/_form.html.haml
= form_for @foot, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .control-group
    = f.label :description, :class => 'control-label'
    .controls
      = f.text_field :description, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), foots_path, :class => 'btn'

app/views/foots/edit.html.erb
<h1>Editing foot</h1>

<%= render 'form' %>

<%= link_to 'Show', @foot %> |
<%= link_to 'Back', foots_path %>

app/views/foots/edit.html.haml
- model_class = Foot
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/foots/index.html.erb
<h1>Listing foots</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @foots.each do |foot| %>
  <tr>
    <td><%= foot.name %></td>
    <td><%= foot.description %></td>
    <td><%= link_to 'Show', foot %></td>
    <td><%= link_to 'Edit', edit_foot_path(foot) %></td>
    <td><%= link_to 'Destroy', foot, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Foot', new_foot_path %>

app/views/foots/index.html.haml
- model_class = Foot
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:description)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @foots.each do |foot|
      %tr
        %td= link_to foot.id, foot_path(foot)
        %td= foot.name
        %td= foot.description
        %td=l foot.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_foot_path(foot), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), foot_path(foot), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_foot_path, :class => 'btn btn-primary'

app/views/foots/new.html.erb
<h1>New foot</h1>

<%= render 'form' %>

<%= link_to 'Back', foots_path %>

app/views/foots/new.html.haml
- model_class = Foot
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/foots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @foot.name %>
</p>

<p>
  <b>Description:</b>
  <%= @foot.description %>
</p>


<%= link_to 'Edit', edit_foot_path(@foot) %> |
<%= link_to 'Back', foots_path %>

app/views/foots/show.html.haml
- model_class = Foot
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @foot.name
%p
  %strong= model_class.human_attribute_name(:description) + ':'
  %br
  = @foot.description

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), foots_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_foot_path(@foot), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), foot_path(@foot), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/hola/caluroso.html.haml
=for i in 0..@valor 
  %p
    = 'Hola Mundo ' + i.to_s

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dinning</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/dinning.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Dinning" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Dinning</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <div class="row">
           <div class="span9">
              <%= yield %>
            </div>
            <div class="span3">
              <div class="well sidebar-nav">
                <h3>Sidebar</h3>
                <ul class="nav nav-list">
                  <li class="nav-header">Sidebar</li>
                  <li><%= link_to "Link1", "/path1"  %></li>
                  <li><%= link_to "Link2", "/path2"  %></li>
                  <li><%= link_to "Link3", "/path3"  %></li>
                </ul>
              </div><!--/.well -->
            </div><!--/span-->
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>